name: CI Backend Movie

on:
  push:
    branches:
      - main
      - "feat/**"
  pull_request:
    branches:
      - main

jobs:
  validar-backend:
    name: Validar Backend
    runs-on: ubuntu-latest
    steps:
      - name: Obtener código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Instalar dependencias Backend
        run: npm ci

      - name: Verificar calidad Backend
        run: npm run lint --if-present

      - name: Ejecutar pruebas Backend
        run: npm test

      - name: Construir Backend
        run: npm run build --if-present
